POST http://localhost:4000/v0/register
content-type: application/json

{
    "firstName" : "Aang",
    "lastName" :  "Avatar",
    "email" :   "aang@avatar.com",
    "password" : "aangavatar98"
}

###

POST http://localhost:4000/v0/login
content-type: application/json

{
    "email" :   "zaheer@avatar.com",
    "password" : "zaheeravatar98"
}

###

POST http://localhost:4000/v0/getuser
content-type: application/json

{
    "firstName" : "Zaheer",
    "lastName" :  "Avatar",
    "email" :   "zaheer2@avatar.com",
    "password" : "zaheeravatar98"
}

###

POST http://localhost:4000/v0/email
content-type: application/json
Authorization: jwt eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InphaGVlckBhdmF0YXIuY29tIiwicGFzc3dvcmQiOiJ6YWhlZXJhdmF0YXI5OCIsImlhdCI6MTY3MzE2OTI5NCwiZXhwIjoxNjczMTcyODk0fQ.MridUfXOx3xriEXIdCBcnhcEMH2gbfLiSyv8yh9_Qrk

{
    "from" : "zaheer@avatar.com",
    "to" :  "aang@avatar.com",
    "subject" :   "I'm not the real avatar!",
    "contents" : "Dear Aang, Im the real avatar and\n you arent."
}


###
